website: hypi.co
name: eman-hypi-cli
label: Test hypi cli
releases:
  - name: latest
    schema:
      types: schema.graphql
    status: PUBLISHED
    notes: latest version
    hypi:
      id: 01F2KYH6ZMXNTVPNRWHHNJ8AMD
hypi:
  id: 01F2KYH6Y33ZEB3VK6RZGJV476
