name: tyty
label: tyty
hypi:
  id: 01F3KDPPEKH26TXXADXC0F0Z1M
releases:
  - name: latest
    schema:
      types: schema.graphql
    status: PUBLISHED
    notes: latest version
    hypi:
      id: 01F3KDPPEPVV4X4FDB361VJ2RN
