website: hhh.com
name: hhd
label: hhh
releases:
  - name: latest
    schema:
      types: schema.graphql
    status: PUBLISHED
    notes: latest version
    hypi:
      id: 01F33TPQCRYV3XKYBEMH1ZAT3Y
hypi:
  id: 01F33TPQCN18XK4YKJB1TZKQ0Y
