targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - .hypi/generated-schema.graphql
      - generated-schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: .hypi/generated-schema.graphql
              output: lib/models/graphql/graphql_api.dart
              queries_glob: graphql/*.graphql
              naming_scheme: pathedWithFields
