targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - .hypi/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: .hypi/full-schema.graphql
              queries_glob: graphql/*.graphql
              output: lib/models/graphql/graphql_api.dart
              naming_scheme: pathedWithFields